service: food-111111
provider:
    name: aws
    region: eu-west-1

        
plugins:
    - serverless-lift

# Exclude files from deployment
package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'
    - '!apienv/**'
    - '!__pycache__/**'


constructs:
    landing:
        type: single-page-app
        path: ""
            


	
