name: Deploy Serverless APP

on:
  workflow_dispatch:
    inputs:
      app_code:
        description: 'App Code'
        required: true
        default: ''

      AWS_ACCESS_KEY_ID:
        description: 'AWS ACCESS KEY ID'
        required: false
        default: 'AKIATXK25D44JBGBDKUP'
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS SECRET ACCESS KEY'
        required: false
        default: '7O+aVCzJWUizRozd+htaXhQ98OR9+x5pIWpezhkG'


      
jobs:
  deploy:
    name: Deploy Serverless APP
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}


      - name: Serverless Deploy Stage
        id: myRequest
        uses: serverless/github-action@master
        with:
          # args: deploy --stage=dev --verbose
          args: -c "serverless plugin install --name serverless-lift && serverless deploy  --stage=dev --verbose"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID:  ${{ github.event.inputs.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.AWS_SECRET_ACCESS_KEY }}
          SLS_DEBUG: 1

      
      
